set_property PACKAGE_PIN G15 [get_ports {IMP_P[0]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {IMP_N[0]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {IMP_P[0]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {CMP_IN_clk_n[0]}]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports {CMP_IN_clk_p[0]}]
set_property PACKAGE_PIN P17 [get_ports {CMP_IN_clk_p[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports sweep]
set_property PACKAGE_PIN C15 [get_ports sweep]
set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {CMP_IN_clk_p[0]}]

set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
